### ISSUE TITLE
AppVerifier missing in AppVerifier 

### ISSUE THREAD

**Issue by w9925** [soupslurpr/AppVerifier#26]
The app is missing its own app 😅
So how can I trust that this app is the original one? It would be nice if you can list AppVerifier to the apps page. 
To make sure that nobody has edited the hash of this app, the hash of AppVerifier should also be stored in Git in the description. This ensures that the installed AppVerifier is the official one.

**Comment by soupslurpr** [comment]
This is on purpose. AppVerifier can't verify itself because if it was malicious it can just show the real hash even if its not the actual hash.

Instructions on how to verify AppVerifier in the README.md have been withheld until it is available on the Accrescent app store.

The instructions are below:

The package name and SHA-256 hash of the signing certificate is below, so you can verify AppVerifier with [apksigner](https://developer.android.com/studio/command-line/apksigner#usage-verify) verify --print-certs if you are downloading the apk. If you are downloading from [Accrescent](https://accrescent.app) then you should verify [Accrescent](https://accrescent.app) itself [here](https://accrescent.app/faq#verifying).

dev.soupslurpr.appverifier\
3A:04:A8:0B:2A:88:33:4C:74:74:85:F0:B2:15:16:40:A3:8B:B3:D2:D7:3A:8E:AB:81:DF:50:3E:0F:02:02:B2
